name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read  # Required to checkout code
  packages: write  # Required to push to GitHub Container Registry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: npm install

    - run: |
        # Start the Node.js app in the background
        nohup node app.mjs &

    - run: |
        # Wait for the server to be up and running (you can adjust the timeout if needed)
        npx wait-on http://localhost:3000
        curl -XPOST -H 'Authorization: Bearer test-token' 'http://localhost:3000/create-container'
